### ISSUE TITLE
Pycups issue with python 3.11

### ISSUE THREAD

**Issue by deetungsten** [chuckcharlie/cups-avahi-airprint#15]
Py-cups is not showing up for me for Python 3.11/ Pip. Is there a reason why you are installing it via pip instead with apk? I simply added pycups to the list of packages (py3-pycups) and it works as well.

**Comment by chuckcharlie** [comment]
“Because we’ve always done it this way.” 🙂
I’ll take a look. Thanks for letting me know!

**Comment by chuckcharlie** [comment]
This was added in the last release. Thanks!
